language: julia

os:
  - linux
  
dist: focal

jdk:
  - openjdk8

julia:
  - 1.5.3
  
env:
  - JULIA_COPY_STACKS=0
  - JULIA_COPY_STACKS=1
  
before_install:
  - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein && mv lein /usr/bin
  - echo $(lein)

notifications:
  email: false
