language: julia

os:
  - linux
  - osx
  - windows

dist: focal

# Windows needs this, linux and osx do not
addons:
  apt:
    packages:
    - openjdk-8-jre
  

julia:
  - 1.5.3
  
env:
  - JULIA_COPY_STACKS=0
  - JULIA_COPY_STACKS=1
  
before_install:
  - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
  - chmod a+x lein
  - echo $($TRAVIS_BUILD_DIR/lein)
  - export JULIA_HOME=$TRAVIS_HOME/julia


script:
  - $TRAVIS_BUILD_DIR/lein test

notifications:
  email: false

cache:
  directories:
  - "$HOME/.m2"
