language: julia

os:
  - linux
  
dist: focal

jdk:
  - openjdk8

julia:
  - 1.5.3
  
env:
  - JULIA_COPY_STACKS=0
  - JULIA_COPY_STACKS=1
  - LEIN_PATH="$TRAVIS_BUILD_DIR/lein"
  
before_install:
  - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
  - echo $($LEIN_PATH)


script:
  - $LEIN_PATH test

notifications:
  email: false
