language: julia

os:
  - linux
  
dist: focal

jdk:
  - openjdk8

julia:
  - 1.5.3
  
env:
  - JULIA_COPY_STACKS=0
  - JULIA_COPY_STACKS=1

    - LEIN_PATH="$TRAVIS_BUILD_DIR/lein"
  
before_install:
  - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
  - chmod a+x lein
  - echo $($TRAVIS_BUILD_DIR/lein)


script:
  - $TRAVIS_BUILD_DIR/lein test

notifications:
  email: false
