language: julia

os:
  - linux
  - osx
  - windows

dist: focal


julia:
  - 1.5.3
  
env:
  - JULIA_COPY_STACKS=0
  - JULIA_COPY_STACKS=1
  
before_install:
  - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
  - chmod a+x lein
  - export JULIA_HOME=$TRAVIS_HOME/julia
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install jdk8; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export PATH=$PATH:"/c/Program Files/Java/jdk1.8.0_221/bin"; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then java -version; fi
  - echo $($TRAVIS_BUILD_DIR/lein)

script:
  - $TRAVIS_BUILD_DIR/lein test

notifications:
  email: false

jobs:
  allow_failures:
    - os: windows

cache:
  directories:
  - "$HOME/.m2"
